### ISSUE TITLE
Defination of rules for measures

### ISSUE THREAD

**Issue by kinjal-codes** [pophealth/quality-measure-engine#10]
First of all thanks a lot for opensource project pophealth 

This is not really an issue but couldn't find any other place for my question I am trying to figure out where the rules are placed in code for different measure but couldn't find . Can you please explain where rules for different measures are stored ?

Thanks

**Comment by eedrummer** [comment]
The source code for the measure definitions is available in the measure bundle. Since the measure definitions are under different licensing terms, they can not be included in this source code repository.

You can find the source code for the Meaningful Use Stage 2 CQMs by following the instructions for importing the measure bundle in the popHealth install guide: https://github.com/pophealth/popHealth/wiki/Installation-v2.1#7-import-the-measure-bundle

In the future, please ask questions like this on the popHealth mailing list: https://groups.google.com/forum/#!forum/pophealth-talk The issue tracker should only be used to report defects found in the software itself.
